import java.util.Scanner;// Needed for a Scanner object
import java.util.Random;// Needed for Random object

/**
 * This program generates a random number and asks the user to guess the number.
 * If the guessed number matches the generated random number we ask user if they
 * want to play again. If the generated number does not match the user input, we
 * suggest the user if the number was too high or too low and keep asking user
 * for more guesses.
 *
 * @author Aishwarya
 * @version 1.0
 * */

public class GuessGame
{
	/**
 	* Prompts user to guess a random number generated by the game. If the guess
 	* is not correct, the game suggests the user if the number is too high or too
 	* low.
 	*
 	* @param args A string array containing the command line arguments.
	*/
	public static void main(String[] args)
	{
		int randomNumber, userInput; // Declaring int variales
		String userResponse; // Declaring String inputs
		char input = 'y'; //Declaring char variable

		System.out.println("\n\nThe GuessGame program plays a guessing game. The "
							+ "program will choose a \"random\"\nnumber between 1-100"
							+ " and give you a chance to guess the number. You will "
							+ "be\ngiven an unlimited number of guesses and on each "
							+ "guess, you will be told\nwhether your guess is too "
							+ "high, too low, or correct. You will have the chance\n"
							+ "to repeat the game as many times you wish.\n\n");

		System.out.println("Let's begin...\n\n");

		//Create a Scanner object for user input.
		Scanner keyboard = new Scanner(System.in);

		//Create a Random class object.
		Random rand = new Random();
	
		//Generate a random number between 0 & 100.
		randomNumber = rand.nextInt(100);

		/*
 		* Ask user to input a number between 1-100, untill you find an exact match
 		*/
		do 
		{
			//Get a number from user
			System.out.print("Guess a number between 1-100: ");
			userInput = keyboard.nextInt();
			keyboard.nextLine();

			if (randomNumber == userInput)
			{
				System.out.println("Your guess is correct!\n\n");
				System.out.print("Would you like to guess another number (y/n)? ");
				userResponse = keyboard.nextLine();
			   input = userResponse.charAt(0);
				
				// Generate a new random number if user hits y or Y
				if(input == 'y' || input == 'Y')
				{
					randomNumber = rand.nextInt(100);
				}
				System.out.println();
			}
			else
			{
				if(randomNumber < userInput)
				{
					System.out.print("Your guess is too high. Try again.\n");
				}
				else
				{
					System.out.print("Your guess is too low. Try again.\n");
				}
			}
		} while((randomNumber != userInput) && (input == 'y' || input == 'Y'));	
	
		System.out.println("\nThanks for playing the GuessGame!\n\n");
		keyboard.close();//Close Scanner
	}
}
